<?php echo $this->doctype() ?>
<html lang="pt_BR">
    <!-- backend default -->
    <head>
        <meta name="robots" content="noindex">
        <meta name="author" content="DB9 - Tecnologia de Dados">
        <meta name="description" content="Software desenvolvido por Skysearch em parceria com a DB9 Tecnologia de Dados">
        <?php
        echo $this->placeholder('base');
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headStyle();
        echo $this->headScript();
        ?>
        <!--[if IE]>
            <link href="<?php echo $this->skin; ?>/css/ie.css" media="screen" rel="stylesheet" type="text/css">
        <![endif]-->   
    </head>
    <body>
        <div class="container">
            <div class="top">
                <h1 class="logo"><span>skySearch</span></h1>
                <?php echo $this->action('box-user', 'layout', 'admin'); ?>    
            </div>
            <div class="menu">
                <?php echo $this->action('menu-system', 'layout', 'admin'); ?> 
            </div>
            <?php echo $this->messages; ?>
            <div id="content" class="system">
                <div class="breadcrumbs">
                    <?php echo $this->navigation()->breadcrumbs(); ?>  
                </div>
                <h1><span><?php echo $this->escape($this->title); ?></span></h1>
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>