<div class="buttons-right">
    <a href="<?php echo $this->url(array('action'=>'index','controller'=>'user','module'=>'api'),null,true);?>" role="button">Listar usuários</a>
    <a href="<?php echo $this->url(array('action' => 'adicionar','controller'=>'user','module'=>'api'),null,true); ?>" role="button">Novo usuário</a>
</div>
<?php echo $this->form; ?>
<?php echo $this->action('alterar-senha','user','api',array('id'=>$this->user_id));?>