<table cellpadding="0" cellspacing="0" border="0" class="display" id="user_list_api">
    <thead>
        <tr>
            <th width="3%">Id</th>
            <th width="34%">Nome</th>
            <th width="20%">E-mail</th>
            <th width="10%">Usuário</th>
            <th width="13%">Nível</th>
            <th width="10%">Status</th>
            <th width="5%"></th>
            <th width="5%"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="8" class="dataTables_empty">Carregando dados do servidor</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="8"></th>
        </tr>
    </tfoot>
</table>
<?php echo $this->dataTables('#user_list_api'); ?>