<div class="buttons-right">
    <a href="<?php echo $this->url(array('action' => 'listar','controller'=>'ticket','module'=>'helpdesk'),null,true); ?>" role="button" class="list"><i class="fa fa-tags"></i> Lista de Chamados</a>
    <a href="<?php echo $this->url(array('action' => 'adicionar','controller'=>'ticket','module'=>'helpdesk'),null,true); ?>" role="button" class="new"><i class="fa fa-tag"></i> Novo Chamado</a>
</div>