<?php 
echo $this->partial('ticket/list/_buttons.phtml');
?>
<?php echo $this->form; ?>
<?php 
if(count($this->tikets)>0) {
?>
<h2>Chamados</h2>

<table class="data-table">
    <thead>
        <tr>
            <th>Assunto</th>
            <th width="10%">Operador</th>
            <th width="11%">Data da Solicitação</th>
            <th width="11%">Prazo</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach($this->tikets as $row) {
        ?>
        <tr>
            <td>
                <?php 
                if($row['status']=='novo-chamado') { 
                    echo '<i class="fa fa-envelope"></i> ';
                } else if($row['status']=='em-andamento') {
                    echo '<i class="fa fa-envelope-o"></i>';
                }
                ?>
                <a href="<?php echo $this->url(array('action'=>'andamento','id'=>$row['ticket_id'])); ?>"><?php echo $this->translate($row['assunto']); ?></a>
            </td>
            <td><?php echo $this->escape($row['operador_nome']);?></td>
            <td><?php echo $row['created']->format('d/m/Y H:i');?></td>
            <td><?php echo $row['prazo']->format('d/m/Y H:i');?></td>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
<?php 
}

