<div id="auth-user" title="Autenticação">
    <h1><span>Autenticação</span></h1>
    <?php
    echo $this->form_login;
    ?>
    <!--[if IE]>
        <div id="navegadores">
            <p>Você está utilizando uma versão do Internet Explorer, 
                algumas funcionalidade do sistema podem aparecer desabilitadas para você.</p>
            <p>Para utilizar o sistema de forma mais estável e segura, utilize um dos navegadores abaixo.</p>
            <p class="icons">
                <a class="firefox icon" href="http://www.mozilla.org/pt-PT/firefox/new/" target="_blank"><span>Firefox</span></a>
                <a class="chrome icon" href="https://www.google.com/intl/pt_br/chrome/browser/" target="_blank"><span>Google Chrome</span></a>
                <a class="safari icon" href="http://www.apple.com/br/safari/" target="_blank"><span>Apple Safari</span></a>
            </p>
        </div>
    <![endif]-->
</div>