<?php 
echo $this->partial('ticket/list/_buttons.phtml');
?>

<?php 
if(count($this->tikets_novos)>0) {
?>
<h2>Novos Chamados</h2>
<table class="data-table">
    <thead>
        <tr>
            <th width="50%">Solicitação</th>
            <th width="10%">Solicitante</th>
            <th width="10%">Operador</th>
            <th width="12%">Data da Solicitação</th>
            <th width="12%">Prazo</th>
            <!--<th width="8%"></th>-->
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach($this->tikets_novos as $row) {
        ?>
        <tr>
            <td>
                <?php 
                if($row['status']=='novo-chamado') { 
                    echo '<i class="fa fa-envelope"></i> ';
                }
                ?>
                <a href="<?php echo $this->url(array('action'=>'andamento','id'=>$row['ticket_id'])); ?>"><?php echo $this->translate($row['assunto']); ?></a>
            </td>
            <td><?php echo $this->translate($row['cliente']);?></td>
            <td><?php echo $this->escape($row['operador_nome']);?></td>
            <td><?php echo $row['created']->format('d/m/Y H:i');?></td>
            <td><?php echo $row['prazo']->format('d/m/Y');?></td>
            <!--<td><a href="<?php echo $this->url(array('action'=>'editar','id'=>$row['ticket_id'])) ?>"><i class="fa fa-pencil"></i> Editar</a></td>-->
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
<?php 
} 
?>

<?php 
if(count($this->tikets)>0) {
?>
<h2>Chamados em Andamento</h2>
<table class="data-table">
    <thead>
        <tr>
            <th width="50%">Solicitação</th>
            <th width="10%">Solicitante</th>
            <th width="10%">Operador</th>
            <th width="12%">Data da Solicitação</th>
            <th width="12%">Prazo</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach($this->tikets as $row) {
        ?>
        <tr>
            <td>
                <?php 
                if($row['status']=='novo-chamado') { 
                    echo '<i class="fa fa-envelope"></i> ';
                } else if($row['status']=='em-andamento') {
                    echo '<i class="fa fa-comment-o"></i>';
                }
                ?>
                <a href="<?php echo $this->url(array('action'=>'andamento','id'=>$row['ticket_id'])); ?>"><?php echo $this->translate($row['assunto']); ?></a>
            </td>
            <td><?php echo $this->translate($row['cliente']);?></td>
            <td><?php echo $this->escape($row['operador_nome']);?></td>
            <td><?php echo $row['created']->format('d/m/Y H:i');?></td>
            <td><?php echo $row['prazo']->format('d/m/Y');?></td>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
<?php 
}
?>
<?php
if (count($this->tikets_finalizados) > 0) {
    ?>
    <h2>Chamados Finalizados</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th width="50%">Solicitação</th>
                <th width="10%">Solicitante</th>
                <th width="10%">Operador</th>
                <th width="8%">Data da Solicitação</th>
                <th width="8%">Prazo</th>
                <th width="8%">Data da Finalização</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->tikets_finalizados as $row) {
                ?>
                <tr>
                    <td>
                        <?php
                        if ($row['status'] == 'novo-chamado') {
                            echo '<i class="fa fa-envelope"></i> ';
                        } else if ($row['status'] == 'em-andamento') {
                            echo '<i class="fa fa-envelope-o"></i>';
                        }
                        ?>
                        <a href="<?php echo $this->url(array('action' => 'andamento', 'id' => $row['ticket_id'])); ?>"><?php echo $this->translate($row['assunto']); ?></a>
                    </td>
                    <td><?php echo $this->escape($row['cliente_nome']); ?></td>
                    <td><?php echo $this->translate($row['cliente']);?></td>
                    <td><?php echo $this->escape($row['operador_nome']); ?></td>
                    <td><?php echo $row['created']->format('d/m/Y H:i'); ?></td>
                    <td><?php echo $row['prazo']->format('d/m/Y'); ?></td>
                    <td><?php echo $row['modified']->format('d/m/Y H:i'); ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>
    </table>
    <?php
}
