<?php 
echo $this->partial('ticket/list/_buttons.phtml');
?>

<?php 
if(count($this->tikets_novos)>0) {
?>
<h2>Novos Chamados</h2>
<p>Departamento: <?php echo $this->escape($this->departamento['description']); ?></p>
<table class="data-table">
    <thead>
        <tr>
            <th width="50%">Solicitação</th>
            <th width="6%">Prioridade</th>
            <th width="10%">Solicitante</th>
            <th width="10%">Operador</th>
            <th width="12%">Data da Solicitação</th>
            <th width="12%">Prazo</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach($this->tikets_novos as $row) {
        ?>
        <tr>
            <td>
                <?php 
                if($row['status']=='novo-chamado') { 
                    echo '<i class="fa fa-envelope"></i> ';
                }
                ?>
                <a href="<?php echo $this->url(array('action'=>'andamento','id'=>$row['ticket_id'])); ?>"><?php echo $this->translate($row['assunto']); ?></a>
            </td>
            <td>
                        <h4><?php
                            if ($row['status'] == 'novo-chamado') {
                                echo '<i class="fa fa-envelope"></i> ';
                            } else if ($row['status'] == 'em-andamento') {
                                echo '<i class="fa fa-envelope-o"></i>';
                            }
                            ?>
                            <a href="<?php echo $this->url(array('action' => 'andamento', 'id' => $row['ticket_id'])); ?>"><?php echo $this->translate($row['assunto']); ?></a>
                        </h4>
                        <?php echo $this->escape($row['descricao']); ?>
                    </td>
            <td><?php echo $this->escape($row['cliente_nome']);?></td>
            <td><?php echo $this->escape($row['operador_nome']);?></td>
            <td><?php echo $row['created']->format('d/m/Y H:i');?></td>
            <td><?php echo $row['prazo']->format('d/m/Y H:i');?></td>
        </tr>
        <?php
        }
        ?>
    </tbody>
    <tfoot>
            <tr>
                <td colspan="9"><a class="listar-mais" href="<?php echo $this->url(array('action'=>'listar-mais','controller'=>'ticket','module'=>'helpdesk','status'=>'novo-chamado')); ?>"><i class="fa fa-tasks"></i> Listar mais</a></td>
            </tr>
        </tfoot>
</table>
<?php 
} 
?>

<?php 
if(count($this->tikets)>0) {
?>
<h2>Chamados em Andamento</h2>
<p class="departamento">Departamento: <?php echo $this->escape($this->departamento['description']); ?></p>
<table class="data-table">
    <thead>
        <tr>
            <th width="50%">Solicitação</th>
            <th width="6%">Prioridade</th>
            <th width="10%">Solicitante</th>
            <th width="10%">Operador</th>
            <th width="12%">Data da Solicitação</th>
            <th width="12%">Prazo</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach($this->tikets as $row) {
        ?>
        <tr>
            <td>
                        <h4><?php
                            if ($row['status'] == 'novo-chamado') {
                                echo '<i class="fa fa-envelope"></i> ';
                            } else if ($row['status'] == 'em-andamento') {
                                echo '<i class="fa fa-comment-o"></i>';
                            }
                            ?>
                            <a href="<?php echo $this->url(array('action' => 'andamento', 'id' => $row['ticket_id'])); ?>"><?php echo $this->translate($row['assunto']); ?></a>
                        </h4>
                        <?php echo $this->escape($row['descricao']); ?>
                    </td>
            <td>
                <?php 
                if($row['prioridade']=='urgente') { 
                    echo '<i class="fa fa-exclamation-triangle"></i>';
                } else if($row['prioridade']=='alta') {
                    echo '<i class="fa fa-exclamation-circle"></i>';
                } else if($row['prioridade']=='normal') {
                    echo '<i class="fa fa-sun-o"></i>';    
                } else if($row['prioridade']=='baixa') {
                    echo '<i class="fa fa-circle-o"></i>';
                }
                echo $this->escape($this->translate($row['prioridade']));
                ?>
                </td>
            <td><?php echo $this->escape($row['cliente_nome']);?></td>
            <td><?php echo $this->escape($row['operador_nome']);?></td>
            <td><?php echo $row['created']->format('d/m/Y H:i');?></td>
            <td><?php echo $row['prazo']->format('d/m/Y H:i');?></td>
        </tr>
        <?php
        }
        ?>
    </tbody>
    <tfoot>
            <tr>
                <td colspan="9"><a class="listar-mais" href="<?php echo $this->url(array('action'=>'listar-mais','controller'=>'ticket','module'=>'helpdesk','status'=>'em-andamento')); ?>"><i class="fa fa-tasks"></i> Listar mais</a></td>
            </tr>
        </tfoot>
</table>
<?php 
} 
?>
<?php
if (count($this->tikets_finalizados) > 0) {
    ?>
    <h2>Chamados Finalizados</h2>
    <table class="data-table">
    <thead>
        <tr>
            <th width="50%">Solicitação</th>
            <th width="6%">Prioridade</th>
            <th width="10%">Solicitante</th>
            <th width="10%">Operador</th>
            <th width="8%">Data da Solicitação</th>
            <th width="8%">Prazo</th>
            <th width="8%">Data da Finalização</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach($this->tikets_finalizados as $row) {
        ?>
        <tr>
            <td>
                        <h4>
                            <a href="<?php echo $this->url(array('action' => 'andamento', 'id' => $row['ticket_id'])); ?>"><?php echo $this->translate($row['assunto']); ?></a>
                        </h4>
                        <?php echo $this->escape($row['descricao']); ?>
                    </td>
            <td>
                <?php 
                if($row['prioridade']=='urgente') { 
                    echo '<i class="fa fa-exclamation-triangle"></i>';
                } else if($row['prioridade']=='alta') {
                    echo '<i class="fa fa-exclamation-circle"></i>';
                } else if($row['prioridade']=='normal') {
                    echo '<i class="fa fa-sun-o"></i>';    
                } else if($row['prioridade']=='baixa') {
                    echo '<i class="fa fa-circle-o"></i>';
                }
                echo $this->escape($this->translate($row['prioridade']));
                ?>
                </td>
            <td><?php echo $this->escape($row['cliente_nome']);?></td>
            <td><?php echo $this->escape($row['operador_nome']);?></td>
            <td><?php echo $row['created']->format('d/m/Y H:i');?></td>
            <td><?php echo $row['prazo']->format('d/m/Y H:i');?></td>
            <td><?php echo $row['modified']->format('d/m/Y H:i');?></td>
        </tr>
        <?php
        }
        ?>
    </tbody>
    <tfoot>
            <tr>
                <td colspan="9"><a class="listar-mais" href="<?php echo $this->url(array('action'=>'listar-mais','controller'=>'ticket','module'=>'helpdesk','status'=>'chamado-finalizado')); ?>"><i class="fa fa-tasks"></i> Listar mais</a></td>
            </tr>
        </tfoot>
</table>
    <?php
}
?>
<?php
/*
if (count($this->tikets_finalizados) > 0) {
    ?>
    <h2>Chamados Finalizados</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Assunto</th>
                <th width="6%">Prioridade</th>
                <th width="10%">Solicitante</th>
                <th width="10%">Operador</th>
                <th width="11%">Data da Solicitação</th>
                <th width="11%">Prazo</th>
                <th width="11%">Data da Finalização</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->tikets_finalizados as $row) {
                ?>
                <tr>
                    <td>
                        <?php
                        if ($row['status'] == 'novo-chamado') {
                            echo '<i class="fa fa-envelope"></i> ';
                        } else if ($row['status'] == 'em-andamento') {
                            echo '<i class="fa fa-envelope-o"></i>';
                        }
                        ?>
                        <a href="<?php echo $this->url(array('action' => 'andamento', 'id' => $row['ticket_id'])); ?>"><?php echo $this->escape($row['assunto']); ?></a>
                    </td>
                    <td>
                        <?php
                        if ($row['prioridade'] == 'urgente') {
                            echo '<i class="fa fa-exclamation-triangle"></i>';
                        } else if ($row['prioridade'] == 'alta') {
                            echo '<i class="fa fa-exclamation-circle"></i>';
                        } else if ($row['prioridade'] == 'normal') {
                            echo '<i class="fa fa-sun-o"></i>';
                        } else if ($row['prioridade'] == 'baixa') {
                            echo '<i class="fa fa-circle-o"></i>';
                        }
                        echo $this->escape($this->translate($row['prioridade']));
                        ?>
                    </td>
                    <td><?php echo $this->escape($row['cliente_nome']); ?></td>
                    <td><?php echo $this->escape($row['departamento']); ?></td>
                    <td><?php echo $this->escape($row['operador_nome']); ?></td>
                    <td><?php echo $row['created']->format('d/m/Y H:i'); ?></td>
                    <td><?php echo $row['prazo']->format('d/m/Y H:i'); ?></td>
                    <td><?php echo $row['modified']->format('d/m/Y H:i'); ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>
    </table>
    <?php
}

*/