<div class="buttons-right">
    <a href="<?php echo $this->url(array('action' => 'listar','controller'=>'index','module'=>'downloads'),null,true); ?>" role="button" class="list"><i class="fa fa-folder-open-o"></i> Lista de Pastas</a>
    <a href="<?php echo $this->url(array('action' => 'adicionar','controller'=>'index','module'=>'downloads'),null,true); ?>" role="button" class="new"><i class="fa fa-folder-o"></i> Nova Pasta</a>
</div>
<?php echo $this->form; ?>