<style type="text/css">
    <!--
    h3 {font-weight: bold; font-size: 11pt; margin-bottom: 4mm}
    table {width: 100%; margin-top: 0 !important}
    table tbody th {width: 30%}
    table tbody .diff {background: #fcefa1!important}
    table td table {margin-bottom: 0 !important}
    table td table td div {width:100%; max-width:350px; overflow:hidden;}
    .relatorio-body {clear: both; margin-bottom: 35px; overflow: hidden}
    -->
</style>
<div class="relatorio-body">
    <?php echo $this->list; ?>
</div>    
